version: "3"
services:
  poly-shooters:
    container_name: poly-shooters
    build:
      context: ./
      dockerfile: ./app/cmd/Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ./app:/go/app/app
      - ./go.mod:/go/app/go.mod
      - ./go.sum:/go/app/go.sum
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
    environment:
      - APP_ENV=development

  database:
    image: postgres:alpine
    container_name: database-poly-shooters
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: shooters
    ports:
      - "5445:5432"
    volumes:
      - ./scripts/init_db:/docker-entrypoint-initdb.d/
      - data_db:/var/lib/postgresql/data

  redis:
    image: redis:3.2.10-alpine
    container_name: redis-poly-shooters
    ports:
      - "6381:6379"

volumes:
  data_db: